countryIndexes = [
"Albania",
"Andorra",
"Armenia",
"Australia",
"Austria",
"Azerbaijan",
"Belarus",
"Belgium",
"Bosnia & Herzegovina",
"Bulgaria",
"Croatia",
"Cyprus",
"Czech Republic",
"Denmark",
"Estonia",
"F.Y.R. Macedonia",
"Finland",
"France",
"Georgia",
"Germany",
"Greece",
"Hungary",
"Iceland",
"Ireland",
"Israel",
"Italy",
"Latvia",
"Lithuania",
"Luxembourg",
"Malta",
"Moldova",
"Monaco",
"Montenegro",
"Morocco",
"Norway",
"Poland",
"Portugal",
"Romania",
"Russia",
"San Marino",
"Serbia",
"Serbia & Montenegro",
"Slovakia",
"Slovenia",
"Spain",
"Sweden",
"Switzerland",
"The Netherlands",
"Turkey",
"Ukraine",
"United Kingdom",
"Yugoslavia"
]

for i in range(0, len(countryIndexes)):
	print(i, "|", countryIndexes[i], "|", round(100 * (i * 4)/255, 1))